CREATE OR REPLACE VIEW NAGV_CTCON_FATORCONV AS

SELECT DISTINCT X.SEQPRODUTO      COD_PROD_FORNECEDOR,
       X.DESCCOMPLETA    DESC_COMPL_PRODUTO,
       X.DESCGENERICA    DESC_GENERICA_PRODUTO,
       E.QTDEMBALAGEM    QTD_EMBALAGEM,
       E.EMBALAGEM       EMBALAGEM,
       F.CODNBMSH        NCM,
       LISTAGG(p.CODACESSO, ', ') WITHIN GROUP (ORDER BY p.SEQPRODUTO) COD_EAN,
       E.EMBCONVNFE      CONVERSAO_EMBALAGEM,
       E.FATORCONVEMBNFE FATOR_CONV_EMBALAGEM,
       X.FATORCONVERSAO  FATOR_CONVERSAO

 FROM MAP_PRODUTO X INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = X.SEQFAMILIA
                    INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = X.SEQFAMILIA
                     LEFT JOIN MAP_PRODCODIGO P ON P.SEQPRODUTO = X.SEQPRODUTO AND P.TIPCODIGO = 'E' AND P.INDUTILVENDA = 'S' AND E.QTDEMBALAGEM = P.QTDEMBALAGEM
                     
GROUP BY X.SEQPRODUTO, DESCCOMPLETA, DESCGENERICA, E.QTDEMBALAGEM, E.EMBALAGEM, F.CODNBMSH, E.EMBCONVNFE, E.FATORCONVEMBNFE, X.FATORCONVERSAO;
                     
