ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_NFS AS 

-- Dados de Notas Fiscais (Saidas e Entradas
-- Giuliano em 17/03/2025 

SELECT X.NUMERONF                NRONOTA,
       E.NOMEREDUZIDO            NOMEEMPRESA,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END INDENTRADASAIDA,
       X.SERIENF                 SERIE,
       X.NFECHAVEACESSO          CHAVENFE,
       XI.SEQPRODUTO             CPROD,
       P.DESCCOMPLETA            DESCRICAO,
       XI.CFOP                   CFOP,
       XI.SITUACAONF             CODSTF,
       SUM(XI.QUANTIDADE)        QUANTIDADE,
       SUM(XI.VLRITEM)           VLRITEM,
       XI.PERACRESCST            MVA,
       SUM(XI.VLRICMSOPPROPRIA)  VLRICMSOPPROPRIA,
       XI.PERALIQUOTAICMS        PERALIQUOTAICMS,
       SUM(XI.VLRICMS)           VLRICMS,
       SUM(XI.BASCALCICMSST)     BASCALCICMSST,
       XI.PERALIQUOTAICMSST      PERALIQUOTAICMSST,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRET,
       SUM(XI.VLRBASEICMSRETIDO) VLRBASEICMSRETIDO,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRETIDO,
       XI.INDPAUTAST             INDPAUTAST,
       XI.SEQNF                  SEQUENCIAL,
       X.DTAEMISSAO              DTA

 FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF AND X.NROEMPRESA = XI.NROEMPRESA
                       INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                       INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       INNER JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = X.CODGERALOPER

WHERE 1=1
  AND X.STATUSNF = 'V'
  AND (TIPCGO = 'S' AND X.MODELONF IN (55,59,65) OR TIPCGO = 'E' AND X.MODELONF IN (55) AND STATUSNFE = 4)

  GROUP BY

  CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END,
       X.NUMERONF,
       X.SERIENF,
       X.NFECHAVEACESSO,
       XI.SEQPRODUTO,
       P.DESCCOMPLETA,
       XI.CFOP,
       XI.SITUACAONF,
       XI.PERACRESCST,
       XI.PERALIQUOTAICMS,
       XI.PERALIQUOTAICMSST,
       XI.INDPAUTAST,
       XI.SEQNF, E.NOMEREDUZIDO, X.DTAEMISSAO
       
UNION

SELECT X.NUMERODF                NRNOTA,
       E.NOMEREDUZIDO            NOMEEMPRESA,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELODF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END INDENTRADASAIDA,
       X.SERIEDF                 SERIE,
       X.NFECHAVEACESSO          CHAVENFE,
       XI.SEQPRODUTO             CPROD,
       P.DESCCOMPLETA            DESCRICAO,
       XI.CFOP                   CFOP,
       XI.SITUACAONF             CODSTF,
       SUM(XI.QUANTIDADE)        QUANTIDADE,
       SUM(XI.VLRITEM)           VLRITEM,
       XI.PERACRESCST            MVA,
       SUM(XI.VLRICMSOPPROPRIA)  VLRICMSOPPROPRIA,
       XI.PERALIQUOTAICMS        PERALIQUOTAICMS,
       SUM(XI.VLRICMS)           VLRICMS,
       SUM(XI.BASECALCICMSST)    BASCALCICMSST,
       XI.PERALIQUOTAICMSST      PERALIQUOTAICMSST,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRET,
       SUM(XI.VLRBASEICMSRETIDO) VLRBASEICMSRETIDO,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRETIDO,
       XI.INDPAUTAST             INDPAUTAST,
       XI.SEQNF                  SEQUENCIAL,
       X.DTAMOVIMENTO

 FROM MFL_DOCTOFISCAL X INNER JOIN MFL_DFITEM XI ON XI.SEQNF = X.SEQNF AND X.NROEMPRESA = XI.NROEMPRESA
                        INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = X.CODGERALOPER

WHERE 1=1
  AND X.STATUSDF = 'V'
  AND TIPCGO = 'S' 
  AND X.MODELODF IN (55,59,65)  
  AND C.TIPDOCFISCAL = 'T'

  GROUP BY

  CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELODF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END,
       X.NUMERODF,
       X.SERIEDF,
       X.NFECHAVEACESSO,
       XI.SEQPRODUTO,
       P.DESCCOMPLETA,
       XI.CFOP,
       XI.SITUACAONF,
       XI.PERACRESCST,
       XI.PERALIQUOTAICMS,
       XI.PERALIQUOTAICMSST,
       XI.INDPAUTAST,
       XI.SEQNF, E.NOMEREDUZIDO, X.DTAMOVIMENTO;
  

