CREATE OR REPLACE VIEW NAGV_CTCON_PRODUTO AS

SELECT LPAD(G.NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) CNPJCPFFORN,
       FF.CODACESSO           CODPRODFORNECEDOR,
       DESCCOMPLETA           DESCPRODUTOFORN,
       E.QTDEMBALAGEM         UNIDMEDIDAFORN,
       X.SEQPRODUTO           CODPRODUTOINT,
       E.EMBCONVNFE           UNIDMEDIDAINT,
       E.FATORCONVEMBNFE      UNIDMEDIDACONVERTIDA,
       P.FATORCONVERSAO       FATORCONVERSAO,
       FA.CODNBMSH            NCM,
       (SELECT MAX(A.CODACESSO)
          FROM CONSINCO.MAP_PRODCODIGO A
         WHERE A.TIPCODIGO = 'E'
           AND A.QTDEMBALAGEM = E.QTDEMBALAGEM
           AND A.INDUTILVENDA = 'S'
           AND A.SEQFAMILIA = P.SEQFAMILIA) CODEFETIVADOEAN
      

  FROM MRL_PRODUTOEMPRESA X INNER JOIN MAP_PRODUTO P      ON P.SEQPRODUTO = X.SEQPRODUTO
                            INNER JOIN MAP_FAMILIA FA     ON FA.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN MAP_FAMFORNEC F    ON F.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN GE_PESSOA G        ON G.SEQPESSOA = F.SEQFORNECEDOR
                            INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = P.SEQFAMILIA
                             LEFT JOIN MAP_PRODCODIGO FF  ON FF.SEQPRODUTO = X.SEQPRODUTO AND FF.TIPCODIGO = 'F' AND FF.QTDEMBALAGEM = E.QTDEMBALAGEM
 WHERE 1=1 -- Filtros definidor pela Neides
   AND NROEMPRESA = 8
   AND E.QTDEMBALAGEM = 1
   --AND F.PRINCIPAL = 'S'
   AND X.STATUSCOMPRA = 'A';
