ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_NFS AS 

-- Dados de Notas Fiscais (Saidas e Entradas
-- Giuliano em 17/03/2025 

SELECT CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END 
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END INDENTRADASAIDA,
       E.NOMEREDUZIDO EMPRESA,
       X.NUMERONF,
       X.SERIENF,
       X.NFECHAVEACESSO CHAVENFE,
       XI.SEQPRODUTO CPROD,
       P.DESCCOMPLETA DESCRICAO,
       XI.CFOP,
       NULL CODSTF,
       SUM(XI.QUANTIDADE)        QUANTIDADE,
       SUM(XI.VLRITEM)           VLRITEM,
       XI.PERACRESCST            MVA,
       SUM(XI.VLRICMSOPPROPRIA)  VLRICMSOPPROPRIA,
       XI.PERALIQUOTAICMS        PERALIQUOTAICMS,
       SUM(XI.VLRICMS)           VLRICMS,
       SUM(XI.BASCALCICMSST)     BASCALCICMSST,
       XI.PERALIQUOTAICMSST      PERALIQUOTAICMSST,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRET, 
       SUM(XI.VLRBASEICMSRETIDO) VLRBASEICMSRETIDO,
       SUM(XI.VLRICMSRETIDO)     VLRICMSRETIDO,
       XI.INDPAUTAST,
       XI.SEQNF
       
 FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF AND X.NROEMPRESA = XI.NROEMPRESA
                       INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                       INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       INNER JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = X.CODGERALOPER

WHERE X.DTAEMISSAO >= SYSDATE - 1
  AND X.STATUSNFE = 4
  AND X.STATUSNF = 'V'
  AND (TIPCGO = 'S' AND X.MODELONF IN (55,65) OR TIPCGO = 'E') 
  
  GROUP BY 
  
  CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END 
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END,
       E.NOMEREDUZIDO,
       X.NUMERONF,
       X.SERIENF,
       X.NFECHAVEACESSO,
       XI.SEQPRODUTO,
       P.DESCCOMPLETA,
       XI.CFOP,
       --NULL CODSTF,
       XI.PERACRESCST,
       XI.PERALIQUOTAICMS,
       XI.PERALIQUOTAICMSST,
       XI.INDPAUTAST,
       XI.SEQNF
  

