CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_PARCITIPANTES AS

-- Dados de Participantes 
-- Giuliano em 18/03/2025 

SELECT NROEMPRESA    SEQPESSOA,
       X.NROCGC      CNPJ_CPF,
       X.RAZAOSOCIAL RAZAO_SOCIAL,
       X.ENDERECO    LOGRADOURO,
       X.ENDERECONRO NRO_LOGRADOURO,
       X.BAIRRO      BAIRRO,
       X.CIDADE      CIDADE,
       X.ESTADO      UF,
       X.CEP         CEP,
       X.INSCRESTADUAL  INSCRICAO_ESTADUAO,
       X.INSCRMUNICIPAL INSCRICAO_GOV
       
  FROM GE_EMPRESA X 
