CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_DEPARA AS

-- Dados de Fornecedores 
-- Giuliano em 18/03/2025 

SELECT P.SEQFAMILIA SEQFAMILIA,
       LPAD(G.NROCGCCPF,12,0) CNPJ_FORNEC,
       LPAD(DIGCGCCPF,2,0)    DIG_CNPJ,
       SEQFORNECEDOR          COD_FORNECEDOR,
       NOMERAZAO              RAZAO_SOCIAL_FORNECEDOR,
       DESCCOMPLETA           DESC_COMPL_PRODUTO,
       P.DESCGENERICA         DESC_GENERICA_PRODUTO,
       E.QTDEMBALAGEM         QTD_EMBALAGEM,
       E.EMBALAGEM            EMBALAGEM,
       FA.CODNBMSH            NCM,
       C.CODACESSO            COD_EAN,
       (SELECT MAX(A.CODACESSO)
          FROM CONSINCO.MAP_PRODCODIGO A
         WHERE A.TIPCODIGO = 'E'
           AND A.QTDEMBALAGEM = E.QTDEMBALAGEM
           AND A.INDUTILVENDA = 'S'
           AND A.SEQPRODUTO = X.SEQPRODUTO) EAN_PRINCIPAL,
       D.CATEGORIAN1 CAT_N1,
       D.CATEGORIAN2 CAT_N2,
       D.CATEGORIAN3 CAT_N3,
       D.CATEGORIAN4 CAT_N4,
       D.CATEGORIAN5 CAT_N5,
       DECODE(STATUSCOMPRA, 'A','ATIVO','S','SUSPENSO','I','INATIVO') STATUSCOMPRA

  FROM MRL_PRODUTOEMPRESA X INNER JOIN MAP_PRODUTO P      ON P.SEQPRODUTO = X.SEQPRODUTO
                            INNER JOIN MAP_FAMILIA FA     ON FA.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN MAP_FAMFORNEC F    ON F.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN GE_PESSOA G        ON G.SEQPESSOA = F.SEQFORNECEDOR
                            INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = P.SEQFAMILIA 
                            INNER JOIN MAP_PRODCODIGO C   ON C.SEQPRODUTO = X.SEQPRODUTO AND C.QTDEMBALAGEM = E.QTDEMBALAGEM AND C.TIPCODIGO = 'E' AND C.INDUTILVENDA = 'S'
                            INNER JOIN DIM_CATEGORIA@CONSINCODW D ON D.SEQFAMILIA = P.SEQFAMILIA
 WHERE NROEMPRESA = 8 
   AND E.QTDEMBALAGEM = 1
   AND F.PRINCIPAL = 'S'
   AND X.STATUSCOMPRA = 'A'
