CREATE OR REPLACE VIEW NAGV_CTC_SAT AS
SELECT 'SAT' INDENTRADASAIDA,
       E.NOMEREDUZIDO NOME_EMPRESA,
       XX.DTAMOVIMENTO DTAEMISSAO,
       XX.NROCHECKOUT ECF,
       XX.NUMERODF NUMCFE,
       XX.SERIEDF SERIE,
       XX.NFECHAVEACESSO CHVCFE,
       P.DESCCOMPLETA DESCRICAO,
       NVL(XI.EMBALAGEM,1) UNID,
       XI.QUANTIDADE QTD,
       ROUND((XI.VLRITEM - XI.VLRDESCONTO) / XI.QUANTIDADE,2) VLRUNIT,
       XI.CFOP,
       XI.VLRITEM - XI.VLRDESCONTO VALORTOTAL,
       XI.SITUACAONF CST

  FROM MFL_DOCTOFISCAL XX INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = XX.NROEMPRESA
                          INNER JOIN MFL_DFITEM XI ON XX.SEQNF = XI.SEQNF
                          INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
 WHERE 1=1
   AND XX.STATUSDF = 'V'
   AND XI.STATUSITEM = 'V'
   AND EXISTS (SELECT 1
                     FROM NAGV_BASE_CGO_FINALIDADE PD
                    WHERE PD.TIPO = 'V'
                      AND PD.CGO_LIST = XX.CODGERALOPER)
   AND XX.SERIEDF = 'CF';
