ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_NFS AS 

-- Dados de Notas Fiscais (Saidas e Entradas
-- Giuliano em 17/03/2025 

SELECT X.DTAENTRADA              DTPERIODO,
       X.NUMERONF                NUMDOC,
       X.SERIENF                 SERIE,
       X.MODELONF                CODMODELO,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END INDENTRADASAIDA,
       CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END CODEMITENTE,
       GE.NOMERAZAO              RAZAOSOCIALEMITENTE,
       GE.UF                     UFEMITENTE,
       CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END CODDESTINATARIO,
       DE.NOMERAZAO              RAZAOSOCIALDESTINATARIO,
       DE.UF                     UFDESTINATARIO,
       X.NFECHAVEACESSO          CHAVENFE,
       XI.SEQITEMNF              SEQITEM,
       XI.SEQPRODUTO             CPROD,
       P.DESCCOMPLETA            DESCRICAO,
       XI.CFOP                   CFOP,
       SUBSTR(XI.SITUACAONF, 0,1) CSTORIG,
       SUBSTR(XI.SITUACAONF, 2,2) CSTICMS,
       XI.CODNCM                 NCM,
       XI.CODCEST                CEST,
      (SELECT MAX(CODACESSO) FROM MAP_PRODCODIGO CC WHERE CC.SEQPRODUTO = XI.SEQPRODUTO AND TIPCODIGO = 'E') CODEFETIVADOEAN,
       SUM(XI.QUANTIDADE)             QUANTIDADE,
       XI.QTDEMBALAGEM           UNITARIO,
       SUM(XI.VLRITEM / XI.QUANTIDADE) VALORUNITARIO,
       SUM(XI.VLRITEM)           VALORTOTAL,
       NVL(XI.PERACRESCST,0)     MVA,
       SUM(XI.BASCALCICMSOPPROPRIA) VLRBASEICMSPROP,
       SUM(XI.VLRICMS)           VLRICMS,
       XI.PERALIQUOTAICMSST      PERALIQUOTAICMSST,
       NVL(SUM(XI.VLRICMSRETIDO),0)     VLRICMSRET,
       NVL(SUM(XI.VLRBASEICMSRETIDO),0) VLRBASEICMSRETIDO,
       NVL(XI.INDPAUTAST, 'N')   INDPAUTAST,
       SUM(XI.BASEFCPST)         VLRBCFCPST,
       XI.PERALIQFCPST           VLRPERCFCPST,
       SUM(XI.VLRFCPST)          VLRFCPST,
       SUM(XI.VLRDESCITEM)       DESCONTO,
       SUM(XI.BASCALCICMSST)     VLRBASEICMSST,
       SUM(XI.VLRICMSST)         VLRICMSST,
       0                         REDBC,
       XI.PERALIQUOTAICMS        ALIQUOTAICMS

 FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF AND X.NROEMPRESA = XI.NROEMPRESA
                       INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                       INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       INNER JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = X.CODGERALOPER
                       INNER JOIN GE_PESSOA GE  ON GE.SEQPESSOA = CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END
                       INNER JOIN GE_PESSOA DE  ON DE.SEQPESSOA = CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END


WHERE 1=1
  AND X.STATUSNF = 'V'
  AND (TIPCGO = 'S' AND X.MODELONF IN (55,59,65) AND STATUSNFE = 4 OR TIPCGO = 'E' AND X.MODELONF IN (55))

  GROUP BY
       X.DTAENTRADA              ,
       X.NUMERONF                ,
       X.SERIENF                 ,
       X.MODELONF                ,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELONF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END ,
       CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END ,
       GE.NOMERAZAO              ,
       GE.UF                     ,
       CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END ,
       DE.NOMERAZAO              ,
       DE.UF                     ,
       X.NFECHAVEACESSO          ,
       XI.SEQITEMNF              ,
       XI.SEQPRODUTO             ,
       P.DESCCOMPLETA            ,
       XI.CFOP                   ,
       SUBSTR(XI.SITUACAONF, 0,1),
       SUBSTR(XI.SITUACAONF, 2,2),
       XI.CODNCM                 ,
       XI.CODCEST                ,
       XI.PERACRESCST            ,
       XI.PERALIQUOTAICMSST      ,
       XI.INDPAUTAST             ,
       XI.PERALIQFCPST           ,
       XI.QTDEMBALAGEM           ,
       XI.PERALIQUOTAICMS


UNION


SELECT X.DTAMOVIMENTO            DTPERIODO,
       X.NUMERODF                NUMDOC,
       X.SERIEDF                 SERIE,
       X.MODELODF                CODMODELO,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELODF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END INDENTRADASAIDA,
       CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END CODEMITENTE,
       GE.NOMERAZAO              RAZAOSOCIALEMITENTE,
       GE.UF                     UFEMITENTE,
       CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END CODDESTINATARIO,
       DE.NOMERAZAO              RAZAOSOCIALDESTINATARIO,
       DE.UF                     UFDESTINATARIO,
       X.NFECHAVEACESSO          CHAVENFE,
       XI.SEQITEMDF              SEQITEM,
       XI.SEQPRODUTO             CPROD,
       P.DESCCOMPLETA            DESCRICAO,
       XI.CFOP                   CFOP,
       SUBSTR(XI.SITUACAONF, 0,1) CSTORIG,
       SUBSTR(XI.SITUACAONF, 2,2) CSTICMS,
      '0'                        NCM,
       XI.CODCEST                CEST,
      (SELECT MAX(CODACESSO) FROM MAP_PRODCODIGO CC WHERE CC.SEQPRODUTO = XI.SEQPRODUTO AND TIPCODIGO = 'E') CODEFETIVADOEAN,
             SUM(XI.QUANTIDADE)             QUANTIDADE,

       XI.QTDEMBALAGEM           UNITARIO,
       SUM(XI.VLRITEM / XI.QUANTIDADE) VALORUNITARIO,
       SUM(XI.VLRITEM)           VALORTOTAL,
       NVL(XI.PERACRESCST,0)     MVA,
       SUM(XI.BASCALCICMSOPPROPRIA) VLRBASEICMSPROP,
       SUM(XI.VLRICMS)           VLRICMS,
       XI.PERALIQUOTAICMSST      PERALIQUOTAICMSST,
       NVL(SUM(XI.VLRICMSRETIDO),0)     VLRICMSRET,
       NVL(SUM(XI.VLRBASEICMSRETIDO),0) VLRBASEICMSRETIDO,
       NVL(XI.INDPAUTAST, 'N')   INDPAUTAST,
       SUM(XI.BASEFCPST)         VLRBCFCPST,
       XI.PERALIQFCPST           VLRPERCFCPST,
       SUM(XI.VLRFCPST)          VLRFCPST,
       SUM(XI.VLRDESCONTO)       DESCONTO,
       SUM(XI.BASECALCICMSST)     BASE,
       SUM(XI.VLRICMSST)         ICMSST,
       0                         REDBC,
       XI.PERALIQUOTAICMS        ALIQUOTAICMS


 FROM MFL_DOCTOFISCAL X INNER JOIN MFL_DFITEM XI ON XI.SEQNF = X.SEQNF AND X.NROEMPRESA = XI.NROEMPRESA
                        INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = X.CODGERALOPER
                        INNER JOIN GE_PESSOA GE  ON GE.SEQPESSOA = CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END
                        INNER JOIN GE_PESSOA DE  ON DE.SEQPESSOA = CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END

WHERE 1=1
  AND X.STATUSDF = 'V'
  AND TIPCGO = 'S'
  AND X.MODELODF IN (55,59,65)
  AND C.TIPDOCFISCAL = 'T'
  AND STATUSNFE = 4

  GROUP BY

  X.DTAMOVIMENTO            ,
       X.NUMERODF                ,
       X.SERIEDF                 ,
       X.MODELODF                ,
       CASE WHEN C.TIPCGO = 'S' THEN CASE WHEN X.MODELODF = 55 THEN 'SAIDA_NFE' ELSE 'SAIDA_NFCE' END
            WHEN C.TIPCGO = 'E' THEN 'ENTRADA_NFE' END ,
       CASE WHEN C.TIPCGO = 'S' THEN X.NROEMPRESA ELSE X.SEQPESSOA END ,
       GE.NOMERAZAO              ,
       GE.UF                     ,
       CASE WHEN C.TIPCGO = 'E' THEN X.NROEMPRESA ELSE X.SEQPESSOA END ,
       DE.NOMERAZAO              ,
       DE.UF                     ,
       X.NFECHAVEACESSO          ,
       XI.SEQITEMDF              ,
       XI.SEQPRODUTO             ,
       P.DESCCOMPLETA            ,
       XI.CFOP                   ,
       SUBSTR(XI.SITUACAONF, 0,1) ,
       SUBSTR(XI.SITUACAONF, 2,2) ,
       0                         ,
       XI.CODCEST                ,
       NVL(XI.PERACRESCST,0)     ,
       XI.PERALIQUOTAICMSST      ,
       XI.PERALIQFCPST           ,
       XI.INDPAUTAST             ,
       XI.QTDEMBALAGEM           ,
       XI.PERALIQUOTAICMS

UNION

SELECT X.DTAENTRADA   DTPERIODO,
       X.NRONOTA                 NUMDOC,
       X.SERIE                   SERIE,
       X.CODMODELO               CODMODELO,
       'ENTRADA_NFE'             INDENTRADASAIDA,
       X.SEQPESSOA               CODEMITENTE,
       GE.NOMERAZAO              RAZAOSOCIALEMITENTE,
       GE.UF                     UFEMITENTE,
       X.NROEMPRESA              CODDESTINATARIO,
       DE.NOMERAZAO              RAZAOSOCIALDESTINATARIO,
       DE.UF                     UFDESTINATARIO,
       X.NFECHAVEACESSO          CHAVENFE,
       XI.NROITEM                SEQITEM,
       XI.SEQPRODUTO             CPROD,
       P.DESCCOMPLETA            DESCRICAO,
       XI.CFOP                   CFOP,
       SUBSTR(CODSTF,0,1)        CSTORIG,
       SUBSTR(CODSTF,1,2)        CSTICMS,
      '0'                        NCM,
       0                         CEST,
     (SELECT MAX(CODACESSO) FROM MAP_PRODCODIGO CC WHERE CC.SEQPRODUTO = XI.SEQPRODUTO AND TIPCODIGO = 'E') CODEFETIVADOEAN,
       SUM(XI.QUANTIDADE)        QUANTIDADE,
       SUM(XI.QUANTIDADE)        UNITARIO,
       SUM(XI.VLRITEM / XI.QUANTIDADE) VALORUNITARIO,
       SUM(XI.VLRITEM)           VALORTOTAL,
       NULL                      MVA,
       SUM(XI.VLRBASEICMSPROP)   VLRBASEICMSPROP,
       SUM(XI.VLRICMS)           VLRICMS,
       0                         PERALIQUOTAICMSST,
       0                         VLRICMSRET,
       0                         VLRBASEICMSRETIDO,
       NULL                      INDPAUTAST,
       0                         VLRBCFCPST,
       0                         VLRPERCFCPST,
       0                         VLRFCPST,
       SUM(XI.VLRDESCONTO)       DESCONTO,
       SUM(XI.VLRBASEICMSST)     VLRBASEICMSST,
       0                         VLRICMSST,
       0                         REDBC,
       XI.ALIQICMS               ALIQUOTAICMS


  FROM OR_NFDESPESA X INNER JOIN OR_NFITENSDESPESA XI ON XI.SEQNOTA = X.SEQNOTA
                      INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                      INNER JOIN GE_PESSOA GE  ON GE.SEQPESSOA = X.SEQPESSOA
                      INNER JOIN GE_PESSOA DE  ON DE.SEQPESSOA = X.NROEMPRESA


WHERE 1=1
  AND X.SITUACAO = 'I'
  AND X.CODMODELO IN (55)

 GROUP BY X.DTAENTRADA,
          X.NRONOTA,
          X.SERIE,
          X.CODMODELO,
          X.SEQPESSOA,
          GE.NOMERAZAO,
          GE.UF,
          X.NROEMPRESA,
          DE.NOMERAZAO,
          DE.UF,
          X.NFECHAVEACESSO,
          XI.NROITEM,
          XI.SEQPRODUTO,
          P.DESCCOMPLETA,
          XI.CFOP,
          XI.ALIQICMS,
          SUBSTR(CODSTF,0,1) ,
          SUBSTR(CODSTF,1,2);
