CREATE OR REPLACE VIEW CONSINCO.NAGV_CTCON_FORNECEDORES AS

-- Dados de Fornecedores 
-- Giuliano em 18/03/2025 

SELECT X.SEQPESSOA     SEQPESSOA,
       LPAD(NROCGCCPF,12,0) CNPJCPF,
       LPAD(DIGCGCCPF,2,0)  DIGCPFCNPJ,
       X.NOMERAZAO     RAZAO_SOCIAL,
       X.LOGRADOURO    LOGRADOURO,
       X.NROLOGRADOURO NRO_LOGRADOURO,
       X.BAIRRO        BAIRRO,
       X.CIDADE        CIDADE,
       X.UF            UF,
       X.CEP           CEP,
       X.INSCMUNICIPAL INSCRICAO_ESTADUAL,
       X.INSCRICAORG   INSCRICAO_GOV
       
  FROM GE_PESSOA X INNER JOIN MAF_FORNECEDOR F ON F.SEQFORNECEDOR = X.SEQPESSOA
